#!/bin/bash

#check if current prefix is 64-bit
if [ -d "/home/wineuser/.wine/drive_c/windows/syswow64" ]; then
    rm -drf "/home/wineuser/.wine"
fi

#create 32-bit prefix
WINEPREFIX="/home/wineuser/.wine" WINEARCH=win32 wine wineboot

#install dotnet 4.0
winetricks -q dotnet40

cd /home/bin/deepsound
WINEDEBUG=fixme-all,err-all LIBGL_ALWAYS_SOFTWARE=1 wine ./DeepSound.exe
err_lvl=$?
cd ~/

exit $err_lvl
