#!/bin/bash

if [ "$#" = "0" ]; then
    WINEPREFIX="/home/wineuser/.wine64" WINEDEBUG=fixme-all,err-all wine "/home/bin/id3stego.exe" -h
    exit 0
fi
WINEPREFIX="/home/wineuser/.wine64" WINEDEBUG=fixme-all,err-all wine "/home/bin/id3stego.exe" "$@"
exit $?
