#!/bin/bash

#pyenv init
echo "Initializing virtual environment, this might take a while..."
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#enter virtual environment
pyenv activate venv-31013

#install dependencies
pip -qq install numpy numba alive-progress texttable

#execution
if [ "$#" = "0" ]; then
    python3 -u "/home/bin/mp3-analyzer/src/mp3filestructureanalyser.py" -h
    exit 0
fi
python3 -u "/home/bin/mp3-analyzer/src/mp3filestructureanalyser.py" "$@"
err_lvl=$?

#leave virtual environment
source deactivate

exit $err_lvl
